<?php

use Illuminate\Database\Seeder;

class BookSeeder extends Seeder
{
    public function run()
    {
        DB::table('books')->insert([
            [
                'title' => 'Giáo trình cua gái đại cương', 
                'author' => 'Thích Tán Gái', 
                'number_pages' => 200,
                'category_id' => 1,
                'publish_date' => '2010/01/01',
                'price' => '200.000',
                'image' => 'books/book3.jpg',
                'description' => 'Sách hay',
            ],
            [
                'title' => 'Tôi tài giỏi bạn cũng thế', 
                'author' => 'ADAMKHOO', 
                'number_pages' => 200,
                'category_id' => 2,
                'publish_date' => '2010/01/01',
                'price' => '200.000',
                'image' => 'books/book2.jpg',
                'description' => 'Sách hay',
            ],
            [
                'title' => 'Quẳng gánh lo đi và vui sống', 
                'author' => 'Hồ Đắc Phưong', 
                'number_pages' => 200,
                'category_id' => 3,
                'publish_date' => '2010/01/01',
                'price' => '200.000',
                'image' => 'books/book1.jpeg',
                'description' => 'Sách hay',
            ],
            [
                'title' => 'Đắc nhân tâm', 
                'author' => 'Dancranegie', 
                'number_pages' => 200,
                'category_id' => 3,
                'publish_date' => '2010/01/01',
                'price' => '200.000',
                'image' => 'books/book4.jpeg',
                'description' => 'Sách hay',
            ],
            [
                'title' => 'Trên cả giàu có', 
                'author' => 'Alexander Green', 
                'number_pages' => 200,
                'category_id' => 2,
                'publish_date' => '2010/01/01',
                'price' => '200.000',
                'image' => 'books/book5.jpeg',
                'description' => 'Sách hay',
            ],
            [
                'title' => 'Khác biệt hay là chết', 
                'author' => 'Jack Trout', 
                'number_pages' => 200,
                'category_id' => 3,
                'publish_date' => '2010/01/01',
                'price' => '200.000',
                'image' => 'books/book6.jpg',
                'description' => 'Sách hay',
            ],
            [
                'title' => 'Cấu trúc dữ liệu và giải thuật', 
                'author' => 'Nguyễn Đức Nghĩa', 
                'number_pages' => 200,
                'category_id' => 1,
                'publish_date' => '2010/01/01',
                'price' => '200.000',
                'image' => 'books/ctdl.jpeg',
                'description' => 'Sách hay',
            ],
            [
                'title' => 'Kiến trúc máy tính', 
                'author' => 'Trần Quang Vinh', 
                'number_pages' => 200,
                'category_id' => 1,
                'publish_date' => '2010/01/01',
                'price' => '200.000',
                'image' => 'books/ktmt.jpg',
                'description' => 'Sách hay',
            ],
            [
                'title' => 'Hệ điều hành', 
                'author' => 'Hồ Đắc Phưong', 
                'number_pages' => 200,
                'category_id' => 1,
                'publish_date' => '2010/01/01',
                'price' => '200.000',
                'image' => 'books/hdh.jpeg',
                'description' => 'Sách hay',
            ],
            [
                'title' => 'Nguyên lý hệ điều hành', 
                'author' => 'Bộ giáo dục', 
                'number_pages' => 200,
                'category_id' => 1,
                'publish_date' => '2010/01/01',
                'price' => '200.000',
                'image' => 'books/nlhdh.png',
                'description' => 'Sách hay',
            ],
            [
                'title' => 'Văn học dân gian', 
                'author' => 'Nguyễn Đức Nghĩa', 
                'number_pages' => 200,
                'category_id' => 3,
                'publish_date' => '2010/01/01',
                'price' => '200.000',
                'image' => 'books/vhdg.jpg',
                'description' => 'Sách hay',
            ],
            [
                'title' => 'Quản trị học đại cương', 
                'author' => 'Nguyễn Quang Chương', 
                'number_pages' => 200,
                'category_id' => 2,
                'publish_date' => '2010/01/01',
                'price' => '200.000',
                'image' => 'books/qthdc.jpg',
                'description' => 'Sách hay',
            ],
        ]);
    }
}
